//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/serializer/dom3/DOMStringListImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlSerializerDom3DOMStringListImpl")
#ifdef RESTRICT_OrgApacheXmlSerializerDom3DOMStringListImpl
#define INCLUDE_ALL_OrgApacheXmlSerializerDom3DOMStringListImpl 0
#else
#define INCLUDE_ALL_OrgApacheXmlSerializerDom3DOMStringListImpl 1
#endif
#undef RESTRICT_OrgApacheXmlSerializerDom3DOMStringListImpl

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgApacheXmlSerializerDom3DOMStringListImpl_) && (INCLUDE_ALL_OrgApacheXmlSerializerDom3DOMStringListImpl || defined(INCLUDE_OrgApacheXmlSerializerDom3DOMStringListImpl))
#define OrgApacheXmlSerializerDom3DOMStringListImpl_

#define RESTRICT_OrgW3cDomDOMStringList 1
#define INCLUDE_OrgW3cDomDOMStringList 1
#include "org/w3c/dom/DOMStringList.h"

@class IOSObjectArray;
@class JavaUtilVector;

/*!
 @brief This class implemets the DOM Level 3 Core interface DOMStringList.
 */
@interface OrgApacheXmlSerializerDom3DOMStringListImpl : NSObject < OrgW3cDomDOMStringList >

#pragma mark Public

/*!
 @brief DOM Internal:
  Add a <code>DOMString</code> to the list.
 @param domString A string to add to the list
 */
- (void)addWithNSString:(NSString *)param;

/*!
 - seealso: org.apache.xerces.dom3.DOMStringList
 */
- (jboolean)containsWithNSString:(NSString *)param;

/*!
 - seealso: org.apache.xerces.dom3.DOMStringList
 */
- (jint)getLength;

/*!
 - seealso: org.apache.xerces.dom3.DOMStringList
 */
- (NSString *)itemWithInt:(jint)index;

#pragma mark Package-Private

/*!
 @brief Construct an empty list of DOMStringListImpl
 */
- (instancetype __nonnull)init;

/*!
 @brief Construct an empty list of DOMStringListImpl
 */
- (instancetype __nonnull)initWithNSStringArray:(IOSObjectArray *)params;

/*!
 @brief Construct an empty list of DOMStringListImpl
 */
- (instancetype __nonnull)initWithJavaUtilVector:(JavaUtilVector *)params;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlSerializerDom3DOMStringListImpl)

FOUNDATION_EXPORT void OrgApacheXmlSerializerDom3DOMStringListImpl_init(OrgApacheXmlSerializerDom3DOMStringListImpl *self);

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *new_OrgApacheXmlSerializerDom3DOMStringListImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *create_OrgApacheXmlSerializerDom3DOMStringListImpl_init(void);

FOUNDATION_EXPORT void OrgApacheXmlSerializerDom3DOMStringListImpl_initWithJavaUtilVector_(OrgApacheXmlSerializerDom3DOMStringListImpl *self, JavaUtilVector *params);

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *new_OrgApacheXmlSerializerDom3DOMStringListImpl_initWithJavaUtilVector_(JavaUtilVector *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *create_OrgApacheXmlSerializerDom3DOMStringListImpl_initWithJavaUtilVector_(JavaUtilVector *params);

FOUNDATION_EXPORT void OrgApacheXmlSerializerDom3DOMStringListImpl_initWithNSStringArray_(OrgApacheXmlSerializerDom3DOMStringListImpl *self, IOSObjectArray *params);

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *new_OrgApacheXmlSerializerDom3DOMStringListImpl_initWithNSStringArray_(IOSObjectArray *params) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlSerializerDom3DOMStringListImpl *create_OrgApacheXmlSerializerDom3DOMStringListImpl_initWithNSStringArray_(IOSObjectArray *params);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlSerializerDom3DOMStringListImpl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlSerializerDom3DOMStringListImpl")
