//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/guava/build_result/java/com/google/common/collect/SingletonImmutableSet.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableSet")
#ifdef RESTRICT_ComGoogleCommonCollectSingletonImmutableSet
#define INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableSet 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableSet 1
#endif
#undef RESTRICT_ComGoogleCommonCollectSingletonImmutableSet

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectSingletonImmutableSet_) && (INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableSet || defined(INCLUDE_ComGoogleCommonCollectSingletonImmutableSet))
#define ComGoogleCommonCollectSingletonImmutableSet_

#define RESTRICT_ComGoogleCommonCollectImmutableSet 1
#define INCLUDE_ComGoogleCommonCollectImmutableSet 1
#include "com/google/common/collect/ImmutableSet.h"

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonCollectUnmodifiableIterator;
@class IOSObjectArray;

/*!
 @brief Implementation of <code>ImmutableSet</code> with exactly one element.
 @author Kevin Bourrillion
 @author Nick Kralevich
 */
@interface ComGoogleCommonCollectSingletonImmutableSet : ComGoogleCommonCollectImmutableSet {
 @public
  id element_;
}

#pragma mark Public

- (jboolean)containsWithId:(id)target;

- (NSUInteger)hash;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (jint)size;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype __nonnull)initWithId:(id)element;

- (instancetype __nonnull)initWithId:(id)element
                             withInt:(jint)hashCode;

- (jint)copyIntoArrayWithNSObjectArray:(IOSObjectArray *)dst
                               withInt:(jint)offset OBJC_METHOD_FAMILY_NONE;

- (ComGoogleCommonCollectImmutableList *)createAsList;

- (jboolean)isHashCodeFast;

- (jboolean)isPartialView;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectSingletonImmutableSet)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectSingletonImmutableSet, element_, id)

FOUNDATION_EXPORT void ComGoogleCommonCollectSingletonImmutableSet_initWithId_(ComGoogleCommonCollectSingletonImmutableSet *self, id element);

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableSet *new_ComGoogleCommonCollectSingletonImmutableSet_initWithId_(id element) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableSet *create_ComGoogleCommonCollectSingletonImmutableSet_initWithId_(id element);

FOUNDATION_EXPORT void ComGoogleCommonCollectSingletonImmutableSet_initWithId_withInt_(ComGoogleCommonCollectSingletonImmutableSet *self, id element, jint hashCode);

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableSet *new_ComGoogleCommonCollectSingletonImmutableSet_initWithId_withInt_(id element, jint hashCode) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableSet *create_ComGoogleCommonCollectSingletonImmutableSet_initWithId_withInt_(id element, jint hashCode);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectSingletonImmutableSet)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableSet")
