//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/listeners/MockingProgressListener.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener")
#ifdef RESTRICT_OrgMockitoInternalListenersMockingProgressListener
#define INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener 0
#else
#define INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener 1
#endif
#undef RESTRICT_OrgMockitoInternalListenersMockingProgressListener

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalListenersMockingProgressListener_) && (INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener || defined(INCLUDE_OrgMockitoInternalListenersMockingProgressListener))
#define OrgMockitoInternalListenersMockingProgressListener_

@protocol OrgMockitoInternalListenersMockingProgressListener < JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersMockingProgressListener)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersMockingProgressListener)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalListenersMockingProgressListener")
