//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/Decamelizer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalUtilDecamelizer")
#ifdef RESTRICT_OrgMockitoInternalUtilDecamelizer
#define INCLUDE_ALL_OrgMockitoInternalUtilDecamelizer 0
#else
#define INCLUDE_ALL_OrgMockitoInternalUtilDecamelizer 1
#endif
#undef RESTRICT_OrgMockitoInternalUtilDecamelizer

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalUtilDecamelizer_) && (INCLUDE_ALL_OrgMockitoInternalUtilDecamelizer || defined(INCLUDE_OrgMockitoInternalUtilDecamelizer))
#define OrgMockitoInternalUtilDecamelizer_

@interface OrgMockitoInternalUtilDecamelizer : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (NSString *)decamelizeMatcherWithNSString:(NSString *)className_;

@end

J2OBJC_STATIC_INIT(OrgMockitoInternalUtilDecamelizer)

FOUNDATION_EXPORT void OrgMockitoInternalUtilDecamelizer_init(OrgMockitoInternalUtilDecamelizer *self);

FOUNDATION_EXPORT OrgMockitoInternalUtilDecamelizer *new_OrgMockitoInternalUtilDecamelizer_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalUtilDecamelizer *create_OrgMockitoInternalUtilDecamelizer_init(void);

FOUNDATION_EXPORT NSString *OrgMockitoInternalUtilDecamelizer_decamelizeMatcherWithNSString_(NSString *className_);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilDecamelizer)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalUtilDecamelizer")
