//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/util/RemoveFirstLine.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalUtilRemoveFirstLine")
#ifdef RESTRICT_OrgMockitoInternalUtilRemoveFirstLine
#define INCLUDE_ALL_OrgMockitoInternalUtilRemoveFirstLine 0
#else
#define INCLUDE_ALL_OrgMockitoInternalUtilRemoveFirstLine 1
#endif
#undef RESTRICT_OrgMockitoInternalUtilRemoveFirstLine

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalUtilRemoveFirstLine_) && (INCLUDE_ALL_OrgMockitoInternalUtilRemoveFirstLine || defined(INCLUDE_OrgMockitoInternalUtilRemoveFirstLine))
#define OrgMockitoInternalUtilRemoveFirstLine_

@interface OrgMockitoInternalUtilRemoveFirstLine : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

/*!
 @param text to have the first line removed
 @return less first line
 */
- (NSString *)ofWithNSString:(NSString *)text;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalUtilRemoveFirstLine)

FOUNDATION_EXPORT void OrgMockitoInternalUtilRemoveFirstLine_init(OrgMockitoInternalUtilRemoveFirstLine *self);

FOUNDATION_EXPORT OrgMockitoInternalUtilRemoveFirstLine *new_OrgMockitoInternalUtilRemoveFirstLine_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalUtilRemoveFirstLine *create_OrgMockitoInternalUtilRemoveFirstLine_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalUtilRemoveFirstLine)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalUtilRemoveFirstLine")
