//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/runners/util/TestMethodsFinder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalRunnersUtilTestMethodsFinder")
#ifdef RESTRICT_OrgMockitoInternalRunnersUtilTestMethodsFinder
#define INCLUDE_ALL_OrgMockitoInternalRunnersUtilTestMethodsFinder 0
#else
#define INCLUDE_ALL_OrgMockitoInternalRunnersUtilTestMethodsFinder 1
#endif
#undef RESTRICT_OrgMockitoInternalRunnersUtilTestMethodsFinder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalRunnersUtilTestMethodsFinder_) && (INCLUDE_ALL_OrgMockitoInternalRunnersUtilTestMethodsFinder || defined(INCLUDE_OrgMockitoInternalRunnersUtilTestMethodsFinder))
#define OrgMockitoInternalRunnersUtilTestMethodsFinder_

@class IOSClass;

@interface OrgMockitoInternalRunnersUtilTestMethodsFinder : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (jboolean)hasTestMethodsWithIOSClass:(IOSClass *)klass;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalRunnersUtilTestMethodsFinder)

FOUNDATION_EXPORT void OrgMockitoInternalRunnersUtilTestMethodsFinder_init(OrgMockitoInternalRunnersUtilTestMethodsFinder *self);

FOUNDATION_EXPORT OrgMockitoInternalRunnersUtilTestMethodsFinder *new_OrgMockitoInternalRunnersUtilTestMethodsFinder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalRunnersUtilTestMethodsFinder *create_OrgMockitoInternalRunnersUtilTestMethodsFinder_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalRunnersUtilTestMethodsFinder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalRunnersUtilTestMethodsFinder")
