//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/creation/ClassNameFinder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalCreationClassNameFinder")
#ifdef RESTRICT_OrgMockitoInternalCreationClassNameFinder
#define INCLUDE_ALL_OrgMockitoInternalCreationClassNameFinder 0
#else
#define INCLUDE_ALL_OrgMockitoInternalCreationClassNameFinder 1
#endif
#undef RESTRICT_OrgMockitoInternalCreationClassNameFinder

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalCreationClassNameFinder_) && (INCLUDE_ALL_OrgMockitoInternalCreationClassNameFinder || defined(INCLUDE_OrgMockitoInternalCreationClassNameFinder))
#define OrgMockitoInternalCreationClassNameFinder_

@interface OrgMockitoInternalCreationClassNameFinder : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

+ (NSString *)classNameForMockWithId:(id)mock;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalCreationClassNameFinder)

FOUNDATION_EXPORT void OrgMockitoInternalCreationClassNameFinder_init(OrgMockitoInternalCreationClassNameFinder *self);

FOUNDATION_EXPORT OrgMockitoInternalCreationClassNameFinder *new_OrgMockitoInternalCreationClassNameFinder_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalCreationClassNameFinder *create_OrgMockitoInternalCreationClassNameFinder_init(void);

FOUNDATION_EXPORT NSString *OrgMockitoInternalCreationClassNameFinder_classNameForMockWithId_(id mock);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalCreationClassNameFinder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalCreationClassNameFinder")
