//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/exceptions/PrintableInvocation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoExceptionsPrintableInvocation")
#ifdef RESTRICT_OrgMockitoExceptionsPrintableInvocation
#define INCLUDE_ALL_OrgMockitoExceptionsPrintableInvocation 0
#else
#define INCLUDE_ALL_OrgMockitoExceptionsPrintableInvocation 1
#endif
#undef RESTRICT_OrgMockitoExceptionsPrintableInvocation

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoExceptionsPrintableInvocation_) && (INCLUDE_ALL_OrgMockitoExceptionsPrintableInvocation || defined(INCLUDE_OrgMockitoExceptionsPrintableInvocation))
#define OrgMockitoExceptionsPrintableInvocation_

@protocol OrgMockitoInvocationLocation;

__attribute__((deprecated))
@protocol OrgMockitoExceptionsPrintableInvocation < JavaObject >

- (NSString *)description;

- (id<OrgMockitoInvocationLocation>)getLocation;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoExceptionsPrintableInvocation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoExceptionsPrintableInvocation)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoExceptionsPrintableInvocation")
