//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: src/main/java/org/mockito/internal/stubbing/answers/ThrowsExceptionClass.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalStubbingAnswersThrowsExceptionClass")
#ifdef RESTRICT_OrgMockitoInternalStubbingAnswersThrowsExceptionClass
#define INCLUDE_ALL_OrgMockitoInternalStubbingAnswersThrowsExceptionClass 0
#else
#define INCLUDE_ALL_OrgMockitoInternalStubbingAnswersThrowsExceptionClass 1
#endif
#undef RESTRICT_OrgMockitoInternalStubbingAnswersThrowsExceptionClass

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalStubbingAnswersThrowsExceptionClass_) && (INCLUDE_ALL_OrgMockitoInternalStubbingAnswersThrowsExceptionClass || defined(INCLUDE_OrgMockitoInternalStubbingAnswersThrowsExceptionClass))
#define OrgMockitoInternalStubbingAnswersThrowsExceptionClass_

#define RESTRICT_OrgMockitoStubbingAnswer 1
#define INCLUDE_OrgMockitoStubbingAnswer 1
#include "org/mockito/stubbing/Answer.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class IOSClass;
@protocol OrgMockitoInvocationInvocationOnMock;

@interface OrgMockitoInternalStubbingAnswersThrowsExceptionClass : NSObject < OrgMockitoStubbingAnswer, JavaIoSerializable >

#pragma mark Public

- (instancetype __nonnull)initWithIOSClass:(IOSClass *)throwableClass;

- (id)answerWithOrgMockitoInvocationInvocationOnMock:(id<OrgMockitoInvocationInvocationOnMock>)invocation;

- (IOSClass *)getThrowableClass;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalStubbingAnswersThrowsExceptionClass)

FOUNDATION_EXPORT void OrgMockitoInternalStubbingAnswersThrowsExceptionClass_initWithIOSClass_(OrgMockitoInternalStubbingAnswersThrowsExceptionClass *self, IOSClass *throwableClass);

FOUNDATION_EXPORT OrgMockitoInternalStubbingAnswersThrowsExceptionClass *new_OrgMockitoInternalStubbingAnswersThrowsExceptionClass_initWithIOSClass_(IOSClass *throwableClass) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalStubbingAnswersThrowsExceptionClass *create_OrgMockitoInternalStubbingAnswersThrowsExceptionClass_initWithIOSClass_(IOSClass *throwableClass);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalStubbingAnswersThrowsExceptionClass)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalStubbingAnswersThrowsExceptionClass")
