//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/invocation/realmethod/RealMethod.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalInvocationRealmethodRealMethod")
#ifdef RESTRICT_OrgMockitoInternalInvocationRealmethodRealMethod
#define INCLUDE_ALL_OrgMockitoInternalInvocationRealmethodRealMethod 0
#else
#define INCLUDE_ALL_OrgMockitoInternalInvocationRealmethodRealMethod 1
#endif
#undef RESTRICT_OrgMockitoInternalInvocationRealmethodRealMethod

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalInvocationRealmethodRealMethod_) && (INCLUDE_ALL_OrgMockitoInternalInvocationRealmethodRealMethod || defined(INCLUDE_OrgMockitoInternalInvocationRealmethodRealMethod))
#define OrgMockitoInternalInvocationRealmethodRealMethod_

@class IOSObjectArray;

@protocol OrgMockitoInternalInvocationRealmethodRealMethod < JavaObject >

- (id)invokeWithId:(id)target
 withNSObjectArray:(IOSObjectArray *)arguments;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInvocationRealmethodRealMethod)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInvocationRealmethodRealMethod)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalInvocationRealmethodRealMethod")
