//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/progress/ArgumentMatcherStorageImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalProgressArgumentMatcherStorageImpl")
#ifdef RESTRICT_OrgMockitoInternalProgressArgumentMatcherStorageImpl
#define INCLUDE_ALL_OrgMockitoInternalProgressArgumentMatcherStorageImpl 0
#else
#define INCLUDE_ALL_OrgMockitoInternalProgressArgumentMatcherStorageImpl 1
#endif
#undef RESTRICT_OrgMockitoInternalProgressArgumentMatcherStorageImpl

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalProgressArgumentMatcherStorageImpl_) && (INCLUDE_ALL_OrgMockitoInternalProgressArgumentMatcherStorageImpl || defined(INCLUDE_OrgMockitoInternalProgressArgumentMatcherStorageImpl))
#define OrgMockitoInternalProgressArgumentMatcherStorageImpl_

#define RESTRICT_OrgMockitoInternalProgressArgumentMatcherStorage 1
#define INCLUDE_OrgMockitoInternalProgressArgumentMatcherStorage 1
#include "org/mockito/internal/progress/ArgumentMatcherStorage.h"

@class OrgMockitoInternalProgressHandyReturnValues;
@protocol JavaUtilList;
@protocol OrgHamcrestMatcher;

@interface OrgMockitoInternalProgressArgumentMatcherStorageImpl : NSObject < OrgMockitoInternalProgressArgumentMatcherStorage >
@property (readonly, class) jint TWO_SUB_MATCHERS NS_SWIFT_NAME(TWO_SUB_MATCHERS);
@property (readonly, class) jint ONE_SUB_MATCHER NS_SWIFT_NAME(ONE_SUB_MATCHER);

+ (jint)TWO_SUB_MATCHERS;

+ (jint)ONE_SUB_MATCHER;

#pragma mark Public

- (instancetype __nonnull)init;

- (id<JavaUtilList>)pullLocalizedMatchers;

- (OrgMockitoInternalProgressHandyReturnValues *)reportAnd;

- (OrgMockitoInternalProgressHandyReturnValues *)reportMatcherWithOrgHamcrestMatcher:(id<OrgHamcrestMatcher>)matcher;

- (OrgMockitoInternalProgressHandyReturnValues *)reportNot;

- (OrgMockitoInternalProgressHandyReturnValues *)reportOr;

- (void)reset;

- (void)validateState;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalProgressArgumentMatcherStorageImpl)

inline jint OrgMockitoInternalProgressArgumentMatcherStorageImpl_get_TWO_SUB_MATCHERS(void);
#define OrgMockitoInternalProgressArgumentMatcherStorageImpl_TWO_SUB_MATCHERS 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgMockitoInternalProgressArgumentMatcherStorageImpl, TWO_SUB_MATCHERS, jint)

inline jint OrgMockitoInternalProgressArgumentMatcherStorageImpl_get_ONE_SUB_MATCHER(void);
#define OrgMockitoInternalProgressArgumentMatcherStorageImpl_ONE_SUB_MATCHER 1
J2OBJC_STATIC_FIELD_CONSTANT(OrgMockitoInternalProgressArgumentMatcherStorageImpl, ONE_SUB_MATCHER, jint)

FOUNDATION_EXPORT void OrgMockitoInternalProgressArgumentMatcherStorageImpl_init(OrgMockitoInternalProgressArgumentMatcherStorageImpl *self);

FOUNDATION_EXPORT OrgMockitoInternalProgressArgumentMatcherStorageImpl *new_OrgMockitoInternalProgressArgumentMatcherStorageImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalProgressArgumentMatcherStorageImpl *create_OrgMockitoInternalProgressArgumentMatcherStorageImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalProgressArgumentMatcherStorageImpl)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalProgressArgumentMatcherStorageImpl")
