//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/matchers/MatcherDecorator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalMatchersMatcherDecorator")
#ifdef RESTRICT_OrgMockitoInternalMatchersMatcherDecorator
#define INCLUDE_ALL_OrgMockitoInternalMatchersMatcherDecorator 0
#else
#define INCLUDE_ALL_OrgMockitoInternalMatchersMatcherDecorator 1
#endif
#undef RESTRICT_OrgMockitoInternalMatchersMatcherDecorator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalMatchersMatcherDecorator_) && (INCLUDE_ALL_OrgMockitoInternalMatchersMatcherDecorator || defined(INCLUDE_OrgMockitoInternalMatchersMatcherDecorator))
#define OrgMockitoInternalMatchersMatcherDecorator_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol OrgHamcrestMatcher;

@protocol OrgMockitoInternalMatchersMatcherDecorator < JavaIoSerializable, JavaObject >

- (id<OrgHamcrestMatcher>)getActualMatcher;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalMatchersMatcherDecorator)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalMatchersMatcherDecorator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalMatchersMatcherDecorator")
