//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/guava/build_result/java/com/google/common/hash/MessageDigestHashFunction.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonHashMessageDigestHashFunction")
#ifdef RESTRICT_ComGoogleCommonHashMessageDigestHashFunction
#define INCLUDE_ALL_ComGoogleCommonHashMessageDigestHashFunction 0
#else
#define INCLUDE_ALL_ComGoogleCommonHashMessageDigestHashFunction 1
#endif
#undef RESTRICT_ComGoogleCommonHashMessageDigestHashFunction

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonHashMessageDigestHashFunction_) && (INCLUDE_ALL_ComGoogleCommonHashMessageDigestHashFunction || defined(INCLUDE_ComGoogleCommonHashMessageDigestHashFunction))
#define ComGoogleCommonHashMessageDigestHashFunction_

#define RESTRICT_ComGoogleCommonHashAbstractHashFunction 1
#define INCLUDE_ComGoogleCommonHashAbstractHashFunction 1
#include "com/google/common/hash/AbstractHashFunction.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@protocol ComGoogleCommonHashHasher;

/*!
 @brief <code>HashFunction</code> adapter for <code>MessageDigest</code> instances.
 @author Kevin Bourrillion
 @author Dimitris Andreou
 */
@interface ComGoogleCommonHashMessageDigestHashFunction : ComGoogleCommonHashAbstractHashFunction < JavaIoSerializable >

#pragma mark Public

- (jint)bits;

- (id<ComGoogleCommonHashHasher>)newHasher OBJC_METHOD_FAMILY_NONE;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype __nonnull)initWithNSString:(NSString *)algorithmName
                                   withInt:(jint)bytes
                              withNSString:(NSString *)toString;

- (instancetype __nonnull)initWithNSString:(NSString *)algorithmName
                              withNSString:(NSString *)toString;

- (id)writeReplace;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonHashMessageDigestHashFunction)

FOUNDATION_EXPORT void ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withNSString_(ComGoogleCommonHashMessageDigestHashFunction *self, NSString *algorithmName, NSString *toString);

FOUNDATION_EXPORT ComGoogleCommonHashMessageDigestHashFunction *new_ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withNSString_(NSString *algorithmName, NSString *toString) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonHashMessageDigestHashFunction *create_ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withNSString_(NSString *algorithmName, NSString *toString);

FOUNDATION_EXPORT void ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withInt_withNSString_(ComGoogleCommonHashMessageDigestHashFunction *self, NSString *algorithmName, jint bytes, NSString *toString);

FOUNDATION_EXPORT ComGoogleCommonHashMessageDigestHashFunction *new_ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withInt_withNSString_(NSString *algorithmName, jint bytes, NSString *toString) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonHashMessageDigestHashFunction *create_ComGoogleCommonHashMessageDigestHashFunction_initWithNSString_withInt_withNSString_(NSString *algorithmName, jint bytes, NSString *toString);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonHashMessageDigestHashFunction)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonHashMessageDigestHashFunction")
