//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/invocation/ArgumentsComparator.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalInvocationArgumentsComparator")
#ifdef RESTRICT_OrgMockitoInternalInvocationArgumentsComparator
#define INCLUDE_ALL_OrgMockitoInternalInvocationArgumentsComparator 0
#else
#define INCLUDE_ALL_OrgMockitoInternalInvocationArgumentsComparator 1
#endif
#undef RESTRICT_OrgMockitoInternalInvocationArgumentsComparator

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalInvocationArgumentsComparator_) && (INCLUDE_ALL_OrgMockitoInternalInvocationArgumentsComparator || defined(INCLUDE_OrgMockitoInternalInvocationArgumentsComparator))
#define OrgMockitoInternalInvocationArgumentsComparator_

@class IOSObjectArray;
@class OrgMockitoInternalInvocationInvocationMatcher;
@protocol OrgMockitoInvocationInvocation;

@interface OrgMockitoInternalInvocationArgumentsComparator : NSObject

#pragma mark Public

- (instancetype __nonnull)init;

- (jboolean)argumentsMatchWithOrgMockitoInternalInvocationInvocationMatcher:(OrgMockitoInternalInvocationInvocationMatcher *)invocationMatcher
                                         withOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)actual;

- (jboolean)argumentsMatchWithOrgMockitoInternalInvocationInvocationMatcher:(OrgMockitoInternalInvocationInvocationMatcher *)invocationMatcher
                                                          withNSObjectArray:(IOSObjectArray *)actualArgs;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInvocationArgumentsComparator)

FOUNDATION_EXPORT void OrgMockitoInternalInvocationArgumentsComparator_init(OrgMockitoInternalInvocationArgumentsComparator *self);

FOUNDATION_EXPORT OrgMockitoInternalInvocationArgumentsComparator *new_OrgMockitoInternalInvocationArgumentsComparator_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalInvocationArgumentsComparator *create_OrgMockitoInternalInvocationArgumentsComparator_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInvocationArgumentsComparator)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalInvocationArgumentsComparator")
