//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/antoniocortes/j2objcprj/relases/j2objc/testing/mockito/build_result/java/org/mockito/internal/invocation/CapturesArgumensFromInvocation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalInvocationCapturesArgumensFromInvocation")
#ifdef RESTRICT_OrgMockitoInternalInvocationCapturesArgumensFromInvocation
#define INCLUDE_ALL_OrgMockitoInternalInvocationCapturesArgumensFromInvocation 0
#else
#define INCLUDE_ALL_OrgMockitoInternalInvocationCapturesArgumensFromInvocation 1
#endif
#undef RESTRICT_OrgMockitoInternalInvocationCapturesArgumensFromInvocation

#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (OrgMockitoInternalInvocationCapturesArgumensFromInvocation_) && (INCLUDE_ALL_OrgMockitoInternalInvocationCapturesArgumensFromInvocation || defined(INCLUDE_OrgMockitoInternalInvocationCapturesArgumensFromInvocation))
#define OrgMockitoInternalInvocationCapturesArgumensFromInvocation_

@protocol OrgMockitoInvocationInvocation;

@protocol OrgMockitoInternalInvocationCapturesArgumensFromInvocation < JavaObject >

- (void)captureArgumentsFromWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)i;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalInvocationCapturesArgumensFromInvocation)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalInvocationCapturesArgumensFromInvocation)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif

#pragma clang diagnostic pop
#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalInvocationCapturesArgumensFromInvocation")
